[tool.poetry]
name = "ssb-gis-utils"
version = "0.1.0"
description = "GIS utility functions used at Statistics Norway."
authors = ["Statistics Norway <ort@ssb.no>"]
license = "MIT"
readme = "README.md"
packages = [{include = "gis_utils", from = "src"}]
homepage = "https://github.com/statisticsnorway/ssb-gis-utils"
repository = "https://github.com/statisticsnorway/ssb-gis-utils"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Scientific/Engineering :: GIS",
]

[tool.poetry.urls]
Changelog = "https://github.com/statisticsnorway/ssb-gis-utils/releases"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
geopandas = "^0.12.2"
shapely = "^2.0.1"
pyogrio = "^0.5.1"
pandas = "^1.5.3"
scikit-learn = "^1.2.1"
requests = "^2.28.2"
pyarrow = "^11.0.0"
igraph = "^0.10.4"
networkx = "^3.0"
matplotlib = "^3.7.0"
mapclassify = "^2.5.0"
folium = "^0.14.0"

[tool.poetry.group.dev.dependencies]
black = {extras = ["d", "jupyter"], version = "^23.1.0"}
isort = "^5.12.0"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
coverage = {extras = ["toml"], version = "^7.1.0"}
mypy = "^1.0.1"
pre-commit = "^3.0.4"
pre-commit-hooks = "^4.4.0"
pyupgrade = "^3.3.1"
jupyterlab = "^3.6.1"
jupytext = "^1.14.4"
pandoc = "^2.3"
nbconvert = "^7.2.9"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["gis_utils", "tests"]

[tool.coverage.report]
show_missing = true

[tool.isort]
profile = "black"
lines_after_imports = 2
skip_gitignore = true

[tool.jupytext]
formats = "ipynb,auto:percent"
notebook_metadata_filter = "jupytext.text_representation,-jupytext.text_representation.jupytext_version,-widgets,-varInspector,-kernelspec"
cell_metadata_filter = "-all"

[tool.pytest.ini_options]
  pythonpath = [
   "src"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
